[package]
name = "flutter_rust_bridge"
edition.workspace = true
rust-version = "1.70.0"
version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
bytemuck = "1.11.0"
anyhow = { workspace = true }
chrono = { workspace = true, optional = true }
threadpool = "1.8.1"
lazy_static = { workspace = true }
parking_lot = "0.12.1"
flutter_rust_bridge_macros = { workspace = true }
uuid = { workspace = true, optional = true }
log = "0.4"
backtrace = { workspace = true }
futures = { version = "0.3.29", optional = true }
byteorder = "1.5.0"
delegate-attr = "0.3.0"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
allo-isolate = { workspace = true, features = ["anyhow", "backtrace", "zero-copy"] }
libc = "0.2"
parking_lot = { version = "0.12.1" }
threadpool = { version = "1.8.1" }
dart-sys-fork = "4.1.1"
tokio = { version = "1.34.0", optional = true, features = ["rt-multi-thread"] }

[target.'cfg(target_family = "wasm")'.dependencies]
console_error_panic_hook = { version = "0.1.7", optional = true }
wasm-bindgen = { version = "0.2.81" }
wasm-bindgen-futures = "0.4.39"
js-sys = { version = "0.3.60" }
web-sys = { version = "0.3.58", features = [
    "DedicatedWorkerGlobalScope",
    "MessageEvent",
    "MessagePort",
    "ErrorEvent",
    "Blob",
    "BlobPropertyBag",
    "Worker",
    "Url",
    "BroadcastChannel",
] }

[build-dependencies]
cc = "1.0"
build-target = "0.4.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.32"
cool_asserts = "2.0.3"

[features]
default = ["chrono", "wasm-start", "rust-async"]
uuid = ["dep:uuid", "allo-isolate/uuid"]
chrono = ["dep:chrono", "allo-isolate/chrono"]
wasm-start = ["console_error_panic_hook"]
rust-async = ["dep:tokio", "dep:futures"]
